### ISSUE TITLE
About tag cloud

### ISSUE THREAD

**Issue by nilesh1021** [russelporosky/jQuery.awesomeCloud.plugin#5]
Is there some syntax for awesomeCloud.plugin 
to click on each span item to go to another location?????????
(e.g. word, another I want to click on them)

<div id="wordcloud" style="border:1px solid #f00;height:150px;width:150px;">
    <span data-weight="14">word</span>
    <span data-weight="5">another</span>
    <span data-weight="7">things</span>
    <span data-weight="23">super</span>
    <span data-weight="10">cloud</span>
</div>

<script>
    var settings = {
        "size" : {
            "grid" : 16
        },
        "options" : {
            "color" : "random-dark",
            "printMultiplier" : 3
        },
        "font" : "Futura, Helvetica, sans-serif",
        "shape" : "square"
    }
    $( "#wordcloud" ).awesomeCloud( settings );
</script>

**Comment by ghost** [comment]
Currently no, links are not possible within the rendered word cloud. That is a feature I have planned, but I haven't had much time to work on it lately, I'm sorry to say.

This is issue #2, so feel free to make any responses there :) Thanks!
