### ISSUE TITLE
onclick event

### ISSUE THREAD

**Issue by ghost** [russelporosky/jQuery.awesomeCloud.plugin#7]
Can you add an onclick event so that when a word is clicked on we can register an event handler to do the next action.  For instance if the words were trending words then clicking on them would bring up a search page with that word

**Comment by slaFFik** [comment]
this can be dome via clickable (linkable) words.
Pull request was already done: https://github.com/indyarmy/jQuery.awesomeCloud.plugin/pull/6
Waiting for approval...

**Comment by slaFFik** [comment]
You closed the issue without responding and merging pull request?

**Comment by ghost** [comment]
I did mark this as a duplicate of #6 and closed it because of that, true. I'm making a few other changes and will be updating the repo later today with that merge. Thanks for doing it, too :)

**Comment by slaFFik** [comment]
Great then, thanks :)
